apiVersion: v1
kind: Service
metadata:
  name: app-of-apps
  namespace: default
spec:
  selector:
    app: app-of-apps
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort